# Staking Ledger Allocations in YAML so we can comment as needed

# This file is a simple "key": "value" where key is the github name and the
# value is the quantity of tokens to assign. The tokens are whole tokens so
# when they're translated in the staking ledger they will be multiplied by 1e9

# TODO: setup mainnet alocations.

##
# BELOW ARE ALLOCATIONS FOR TEST ONLY GENESIS DOCUMENTS
##
rvg: "100000"
pro-wh: "100000"
peterjgilbert: "100000"
